source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Clappr_Example' do
  platform :ios, '8.4'
  pod "Clappr", :path => "../"
end

target 'Clappr-tvOS-Example' do
    platform :tvos, '9.0'
    pod "Clappr", :path => "../"
end

target 'Clappr_Tests' do
  pod "Clappr", :path => "../"

  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '~> 4.0.0'
end
