source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Clappr_Example', :exclusive => true do
  pod "Clappr", :path => "../"
end

target 'Clappr_Tests', :exclusive => true do
  pod "Clappr", :path => "../"

  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '~> 4.0.0'
end
