source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Clappr_Example', :exclusive => true do
  pod "Clappr", :path => "../"
end

target 'Clappr_Tests', :exclusive => true do
  pod "Clappr", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end
