public enum Event: String, CaseIterable {
    case didUpdateBuffer
    case didUpdatePosition
    case ready
    case stalling
    case didFindAudio
    case didFindSubtitle
    case didSelectAudio
    case didSelectSubtitle
    case disableMediaControl
    case enableMediaControl
    case didComplete
    case willPlay
    case playing
    case willPause
    case didPause
    case willStop
    case didStop
    case error
    case didUpdateAirPlayStatus
    case requestFullscreen
    case exitFullscreen
    case requestPosterUpdate
    case willUpdatePoster
    case didUpdatePoster
    case willSeek
    case didSeek
    case didChangeDvrStatus
    case seekableUpdate
    case didChangeDvrAvailability
    case didUpdateOptions
    case willShowMediaControl
    case didShowMediaControl
    case willHideMediaControl
    case didHideMediaControl
    case willDestroy
    case didDestroy
    case willLoadSource
    case didLoadSource
    case didNotLoadSource
    case willChangePlayback
    case didChangePlayback
    case willChangeActiveContainer
    case didChangeActiveContainer
    case willChangeActivePlayback
    case didChangeActivePlayback
    case willEnterFullscreen
    case didEnterFullscreen
    case willExitFullscreen
    case didExitFullscreen
    case didUpdateDuration
    case willShowModal
    case didShowModal
    case willHideModal
    case didHideModal
}
