public enum ContainerEvent: String {
    case destroyed = "clappr:container:destroyed"
    case ready = "clappr:container:ready"
    case error = "clappr:container:error"
    case timeUpdated = "clappr:container:time_update"
    case progress = "clappr:container:progress"
    case play = "clappr:container:play"
    case stop = "clappr:container:stop"
    case pause = "clappr:container:pause"
    case ended = "clappr:container:ended"
    case tap = "clappr:container:tap"
    case seek = "clappr:container:seek"
    case volume = "clappr:container:volume"
    case bufferFull = "clappr:container:buffer_full"
    case mediaControlDisabled = "clappr:container:media_control_disabled"
    case mediaControlEnabled = "clappr:container:media_control_enabled"
    case audioSourcesUpdated = "clappr:container:audio_sources_updated"
    case subtitleSourcesUpdated = "clappr:container:subtitle_sources_updated"
    case sourceChanged = "clappr:container:source_changed"
}
